plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
packageExtensions:
  "styled-components@*":
    dependencies:
      "react-is": "*"
  "@nivo/core@*":
    dependencies:
      "@nivo/tooltip": "*"
      "prop-types": "*"
  "@nivo/legends@*":
    dependencies:
      "prop-types": "*"
  "@nivo/calendar@*":
    dependencies:
      "prop-types": "*"
  "@nivo/radar@*":
    dependencies:
      "prop-types": "*"
  "@nivo/colors@*":
    dependencies:
      "prop-types": "*"
  "@blueprintjs/popover2@*":
    dependencies:
      "react-dom": "*"      
  "react-spring@*":
    dependencies:
      "react": "*"
      "react-dom": "*"
      