version: '3'
services:
  psyche-server:
    extends:
      file: common-services.yml
      service: psyche-server
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    command: npm start   

networks:
  default:
    external:
      name: sesame_default
